name: "CFlux CI"

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.6'
          bundler-cache: true

      - name: Prepare environment & Install dependencies
        run: bash bundle-installation
        working-directory: cflux

      - name: Set up database schema
        run: bin/rails db:schema:load
        working-directory: cflux
        
      - name: Run tests
        run: bin/rake
        working-directory: cflux

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.6'
          bundler-cache: true

      - name: Prepare environment
        run: |
          rm -rf vendor/
          bundle config set --local path 'vendor/bundle'
        working-directory: cflux

      - name: Install dependencies
        run: bundle install --verbose
        working-directory: cflux

      - name: Security audit dependencies
        run: bin/bundler-audit --update
        working-directory: cflux

      - name: Security audit application code
        run: bin/brakeman -q -w2
        working-directory: cflux

      - name: Lint Ruby files
        run: bin/rubocop --parallel
        working-directory: cflux
